# Generated by Django 3.0 on 2020-12-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(choices=[('Must', 'Must'), ('Should', 'Should'), ('Could', 'Could'), ('Would', 'Would')], default='Must', max_length=6),
        ),
    ]
