# Generated by Django 3.0 on 2020-12-20 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='time_estimate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
